In [20]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import dctn, idctn

In [21]:
def apply_A(img):
    """Computes p = vert and q = horiz as given above for an input image.
    """
    h_diffs, v_diffs = np.zeros_like(img), np.zeros_like(img)
    h_diffs[:,:-1] = img[:,1:] - img[:,:-1]
    v_diffs[:-1,:] = img[1:,:] - img[:-1,:]

    return v_diffs, h_diffs


def apply_A_T(p, q):
    """Computes A^T(p,q).
    """
    # Get m and n
    M, N = p.shape
    
    # Array for output
    result = np.zeros((M,N))

    # Pad arrays
    q = np.hstack([ np.zeros(M)[:,None], q])
    p = np.vstack([ np.zeros(N)[None,:], p])

    pdiff = p[1:,:] - p[:-1,:]
    pdiff[-1,:] = - p[-2,:]
    qdiff = q[:,1:] - q[:,:-1]
    qdiff[:,-1] = - q[:,-2]

    # Insert result
    result = pdiff + qdiff
    #result = p[:,1:] + q[1:,:] - p[:,:-1] - q[:-1, :] 

    return -result

In [22]:
M = 3
N = 2
img = np.random.normal(size=(M,N))

In [23]:
img[1,0] - img[0,0]

1.6659651278713126

In [24]:
img

array([[-0.97377562,  0.10489085],
       [ 0.69218951, -0.39373236],
       [-1.04862386, -1.08202028]])

In [25]:
apply_A(img)

(array([[ 1.66596513, -0.49862321],
        [-1.74081336, -0.68828792],
        [ 0.        ,  0.        ]]),
 array([[ 1.07866647,  0.        ],
        [-1.08592186,  0.        ],
        [-0.03339642,  0.        ]]))

In [26]:
apply_A(img)

(array([[ 1.66596513, -0.49862321],
        [-1.74081336, -0.68828792],
        [ 0.        ,  0.        ]]),
 array([[ 1.07866647,  0.        ],
        [-1.08592186,  0.        ],
        [-0.03339642,  0.        ]]))

In [27]:
p, q = apply_A(img)
apply_A_T(p, q)

array([[-2.7446316 ,  1.57728968],
       [ 4.49270035, -0.89625715],
       [-1.70741694, -0.72168435]])

In [29]:
for j in range(10):
    x = np.random.normal(size=(M,N))
    y1, y2 = np.random.normal(size=(M,N)), np.random.normal(size=(M,N))
    Rx1, Rx2 = apply_A(x)
    Ry = apply_A_T(y1, y2)
    dot1 = (Rx1*y1 + Rx2*y2).flatten().sum()
    dot2 = (x * Ry).flatten().sum()
    print(f"dot1 = {dot1}")
    print(f"dot2 = {dot2}")
    print(f"")

dot1 = -1.3737805286433682
dot2 = -1.3737805286433684

dot1 = -0.06524678842334586
dot2 = -0.06524678842334591

dot1 = 0.7855510637102511
dot2 = 0.7855510637102512

dot1 = 3.573824156140686
dot2 = 3.5738241561406854

dot1 = 5.374275418776051
dot2 = 5.374275418776053

dot1 = -1.3548687740424252
dot2 = -1.3548687740424252

dot1 = 5.3594474169782576
dot2 = 5.359447416978258

dot1 = -3.9811404448173064
dot2 = -3.981140444817306

dot1 = 4.964051297597077
dot2 = 4.964051297597077

dot1 = 8.119070408209275
dot2 = 8.119070408209273



# Check if diagonalized by DCT?

In [70]:
M, N = 10, 3
v = np.random.normal(size=(M,N))
p, q = apply_A( idctn( v, norm="ortho" ) )
z = apply_A_T(p, q)
res = dctn( z, norm="ortho" )
res = res/v
print(res)

[[2.62475807e-16 1.00000000e+00 3.00000000e+00]
 [9.78869674e-02 1.09788697e+00 3.09788697e+00]
 [3.81966011e-01 1.38196601e+00 3.38196601e+00]
 [8.24429495e-01 1.82442950e+00 3.82442950e+00]
 [1.38196601e+00 2.38196601e+00 4.38196601e+00]
 [2.00000000e+00 3.00000000e+00 5.00000000e+00]
 [2.61803399e+00 3.61803399e+00 5.61803399e+00]
 [3.17557050e+00 4.17557050e+00 6.17557050e+00]
 [3.61803399e+00 4.61803399e+00 6.61803399e+00]
 [3.90211303e+00 4.90211303e+00 6.90211303e+00]]


# It is! we are good to go